config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'static#index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/signup',  to: 'users#new', as: 'signup'

  resources :goals
  resources :events
  resources :habits, only: [:show, :new, :create]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true
  has_many :goals
  has_many :relationships
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                 foreign_key: "followed_id",
                                 dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :habits, through: :goals
  has_many :events, through: :goals

  # Follows a user.
  def follow(other_user)
    following << other_user
  end

  # Unfollows a user.
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

  # number of goals complete

  # number of goals incomplete

  # average goals per week?

  # longest event ever

  # longest streak ever

  # total hours logged
  def all_hours_logged
    all_time = 0
    self.goals.each do |goal|
      all_time += goal.total_time
    end
    "#{all_time / 60} hrs, #{all_time % 60} mins"
  end

  def total_sessions_logged
    all_sessions = 0
    self.goals.each do |goal|
    end
  end

  def total_goals_reached
    self.goals.count { |g| g.completed? }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def following
    @following = User.find(params[:id]).following
  end

  def followers
    @followers = User.find(params[:id]).followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :password)
  end

end

app/views/users/_feed.html.erb
<% if current_user == @user %>
  <ul class="list-inline">
    <% @user.following.each do |follow| %>
      <% follow.events.each do |event| %>
      <div class="feed-box">
        <li id="f-user"><%= link_to follow.name, user_path(follow) %></li>
        <li id="f-descript">Completed <%= "#{event.minutes / 60}" %> hours, <%= "#{event.minutes % 60}" %> minutes of <%= event.goal.habit.name %>.</li>
        <li id="f-complete-since"><%= event.time_since_completion %> ago</li>
      </div>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>

<div class="stats">
    following
    <a href="<%= following_user_path(@user) %>">
      <strong id="following" class="stat">
        <%= @user.following.count %>
      </strong>
    </a> |
    followers
    <a href="<%= followers_user_path(@user) %>">
      <strong id="followers" class="stat">
        <%= @user.followers.count %>
      </strong>
    </a> |
  Hours logged: <%= @user.all_hours_logged %> |
  Goals reached: <%= @user.total_goals_reached %>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/followers.html.erb
<div class="follow">
<h1>Followers</h1>

<ul class="inline-list">
  <% @followers.each do |user| %>
    <li><%= link_to user.name, user_path(user) %></li>
  <% end %>
</ul>
</div>

app/views/users/following.html.erb
<div class="follow">
  <h1>Following</h1>

  <ul class="inline-list">
  <% @following.each do |user| %>
    <li><%= link_to user.name, user_path(user) %></li>
  <% end %>
  </ul>
</div>

app/views/users/index.html.erb
<ul>
<% @users.each do |user| %>
  <li><%= link_to user.name, user_path(user) %></li>
<% end %>
</ul>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<div class="container">

    <!-- <h1><%= @user.name %></h1>
    <div class="">
      <p><%= link_to "New Goal", new_goal_path %> | <%= link_to "New Habit", new_habit_path %> | <%= link_to "All Users", users_path %> | <%= render 'follow_form' if logged_in? %></p>
    </div> -->

  <div class="row mt-5">
    <div class="stats col-12">
      <h3><%= @user.name %></h3>
      <ul class="d-inline-flex list-unstyled">
        <li id="stat-descript" class="pr-5"><%= render 'stats' %></li>
        <li id="stat-descript" class="pr-5"><%= link_to "New Goal", new_goal_path, class: "btn btn-primary btn-sm" %></li>
        <li id="stat-descript" class="pr-5"><%= link_to "New Habit", new_habit_path, class: "btn btn-primary btn-sm" %></li>
        <li id="stat-descript" class="pr-5"><%= link_to "Follow Users", users_path, class: "btn btn-primary btn-sm" %></li>
      </ul>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-7">

      <table class="table table-dark rounders">
        <thead>
          <tr>
            <th scope="col">Habits</th>
            <th scope="col">Hours</th>
            <th scope="col">Sessions</th>
            <th scope="col">Streak</th>
            <th scope="col">Completed</th>
          </tr>
        </thead>
        <tbody>
          <% @user.goals.each do |goal| %>
            <tr>
              <td><%= goal.habit.name %></td>
              <td><%= goal.total_hours %>/<%= goal.target_hours %></td>
              <td><%= goal.total_events %>/<%= goal.target_times %></td>
              <td><%= goal.longest_streak%> / <%= goal.target_streak %></td>
              <td><%= goal.completed? %></td>
              <td><%= link_to "Show", goal_path(goal), class: "btn btn-primary btn-sm" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="feed col-5">
      <h3>Feed</h3>
      <%= render 'feed' %>
    </div>
  </div>
</div>