config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'static#index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/signup',  to: 'users#new', as: 'signup'

  resources :goals
  resources :events
  resources :habits, only: [:show, :new, :create]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
  belongs_to :habit
  has_many :events
  validates_presence_of :target_hours, :target_times, :target_streak

  # calculate total event hours/minutes for this goal
  def total_time
    total_minutes = 0
    self.events[0..-2].each do |event|
      total_minutes += event.minutes
    end
    total_minutes
  end

  def total_hours
    total_minutes = 0;
    self.events.each do |event|
      total_minutes += event.minutes
    end
    "#{total_minutes / 60}"
  end

  # get total event instances
  def total_events
    self.events.count
  end

  # get highest streak (concurrent days) from events
  def longest_streak
    sorted = self.events.sort_by &:date
    result = []
    sorted.each do |event|
      if result.empty? || (event.date - result.last.last.date).to_i != 1
        result << [event]
      else
        result.last << event
      end
    end
      if result == []
        return 0
      else
      result.sort_by {|el| el.length}.last.length
      end
  end

  def completed?
    if self.longest_streak >= self.target_streak && self.total_hours.to_i >= self.target_hours && self.total_events >= self.target_times
      self.complete = true
    else
      self.complete = false
    end
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def new
    @goal = Goal.new
    @habits = Habit.all
  end

  def create
    @goal = Goal.new(goal_params)
    if @goal.valid?
      @goal.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def show
    @goal = Goal.find(params[:id])
    @event = Event.new
    @events = @goal.events
  end

  def edit
    @goal = Goal.find(params[:id])
    @habits = Habit.all

  end

  def update
    @goal = Goal.find(params[:id])
    @goal.update(goal_params)
    redirect_to @goal
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to user_path(current_user)
  end

  private
  def goal_params
    params.require(:goal).permit(:user_id, :habit_id, :target_hours, :target_times, :target_streak)
  end

end

app/views/goals/edit.html.erb
<%= form_for @goal do |f| %>
  <%= f.label :habit %>
  <%= f.collection_select(:habit_id, @habits, :id, :name) %>
  <br>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.label :target_hours %>
  <%= f.number_field :target_hours %>
  <br>
  <%= f.label :target_streak %>
  <%= f.number_field :target_streak %>
  <br>
  <%= f.label :target_times %>
  <%= f.number_field :target_times %>
  <br>
  <%= f.submit %>
<% end %>

app/views/goals/new.html.erb
<div class="new-form">
  <h1>Create new goal</h1>
  <%= form_for @goal do |f| %>
  <div class="form-group">
    <%= f.label :habit %>
    <%= f.collection_select(:habit_id, @habits, :id, :name) %>
  </div>
  <div class="form-group">
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.label :target_hours %>
    <%= f.number_field :target_hours %>
  </div>
  <div class="form-group">
    <%= f.label :target_streak %>
    <%= f.number_field :target_streak %>
  </div>
  <div class="form-group">
    <%= f.label :target_times %>
    <%= f.number_field :target_times %>
  </div>
    <%= f.submit %>
  <% end %>

</div>

app/views/goals/show.html.erb
<div class="container">
<div class="row mt-5">
<div class="goal-show col-4">
  <h1><%= @goal.habit.name %></h1>
  <h2><%= @goal.user.name %></h2>
  <ul class="list-inline">
    <li id="f-descript">Total Time: <%= "#{@goal.total_time / 60}:#{@goal.total_time % 60}" %></li>
    <li id="f-descript">Total Sessions: <%= @goal.total_events %></li>
    <li id="f-descript">Longest Streak: <%= @goal.longest_streak %></li>
  </ul>

  <% if @goal.user == current_user %>
    <%= link_to "Edit Goal", edit_goal_path(@goal), class: "btn btn-primary" %>
    <%= link_to "Delete Goal", goal_path(@goal), method: :delete, class: "btn btn-primary"%>

    <%= form_for @event do |f| %>
      <%= f.number_field :goal_id, value: @goal.id, type: :hidden %>
      <%= f.time_field :start_time, value: Time.now, type: :hidden %>
      <%= f.date_field :date, value: Date.today, type: :hidden %>
      <%= f.submit "Start #{@goal.habit.name}", class: "btn btn-primary" %>
    <% end %>

  <% end %>
  </div>
  <div class="feed col-7">
    <ul class="list-inline">
      <% @goal.events.each do |event| %>
        <div class="feed-box">
          <li id="f-descript">Date: <%= event.date_formatter %></li>
          <li id="f-descript">Start Time: <%= event.start_time.strftime("%R") %></li>
          <% if event.end_time == nil %>
            <li id="f-descript"><%= link_to "End", edit_event_path(event), class: "btn btn-primary" %></li>
          <% else %>
            <li id="f-descript">End Time: <%= event.end_time.strftime("%R") %></li>
            <li id="f-descript">Elapsed Time: <%= event.elapsed_time %></li>
          <% end %>
        </div>
      <% end %>
    </ul>
  </div>
</div>
</div>