config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'static#index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/signup',  to: 'users#new', as: 'signup'

  resources :goals
  resources :events
  resources :habits, only: [:show, :new, :create]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

end

app/models/habit.rb
class Habit < ApplicationRecord
  has_many :goals
  has_many :users, through: :goals
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController

    def show
      @habit = Habit.find(params[:id])
      @user = User.find(current_user.id)
      @goals = @habit.goals
    end

    def new
      @habit = Habit.new
    end

    def create
      @habit = Habit.new(habit_params)
      if @habit.save
        # @goal = Goal.create(user_id: current_user.id, habit_id: @habit.id)
        redirect_to user_path(current_user)
      else
        render :new
      end
    end

    private

    def habit_params
      params.require(:habit).permit(:name)
    end

end

app/views/habits/new.html.erb
<%= form_for @habit do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/habits/show.html.erb
<!-- <div class="">
  <h1><%= @habit.name %></h1>
  <h2><%= @user.name %></h2>
  <ul>
    <li>Total Hours:</li>
    <li>Total Sessions:</li>
    <li>Longest Streak:</li>
  </ul>

  <%= button_to "Start #{@habit.name}", events_path %>

</div> -->